### ISSUE TITLE
Desktop roadmap towards 1.0

### ISSUE THREAD

**Issue by Deathspike** [animeloyalty/animeloyalty#5]
*AnimeLoyalty* desktop is in *preview*. It's not terribly useful as-is, because it's missing fundamental features. It's intended to gather user feedback on the current feature set, and to ensure that the underlying technology behaves correctly. If you're interested in helping out *AnimeLoyalty*, please do install it and provide feedback on the usability and the technology. Thank you!

# Streaming Edition
The 'Streaming Edition' will focus on making streaming feature-complete. This includes:
- [ ] Add settings configuration #4 
- [ ] Add search options #3
- [ ] Add stream quality selection #1 

# Personal Edition
The 'Personal Edition' will focus on adding personal & tracking features. This includes:
- [ ] Adding series to your library and store offline metadata.
- [ ] Updating series in your library (manually and automatically).
- [ ] Marking episode status (watched/unwatched) by episode and season.
- [ ] Tracking episode status (unwatched/watching/watched).
- [ ] Tracking episode progress (continue watching).

# Offline Edition
The 'Offline Edition' will focus on adding offline capabilities. This includes:
- [ ] Add download location to a series.
- [ ] Add download status for a series (all/unwatched/none).
- [ ] Automatically download episodes according to download status.
- [ ] Playback locally downloaded episodes.

**Comment by Deathspike** [comment]
The 'Streaming Edition' is live! This completes the whole feature set that I had planned for streaming functionality. It should be feature-complete and allow you to stream any series in an convenient desktop application. The next step is the 'Personal Edition', which will allow you to add series to your library and track your progress. Stay tuned for more!
